blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig


app_name = BlogConfig.name

urlpatterns = [
    path("blog_list/", views.BlogListView.as_view(), name="blog_list"),
    path("blog_detail/<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("blog_create/", views.BlogCreateView.as_view(), name="blog_create"),
    path("blog_update/<int:pk>/", views.BlogUpdateView.as_view(), name="blog_update"),
    path("blog_delete/<int:pk>/", views.BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class BlogPost(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()
    preview_img = models.ImageField(upload_to="blog/preview_img/")
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    count_views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ['title']
        db_table = "posts_table"

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import BlogPost
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = BlogPost

    def get_queryset(self):
        queryset = super().get_queryset().filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        object_ = super().get_object(queryset)
        object_.count_views += 1
        object_.save()
        return object_


class BlogCreateView(CreateView):
    model = BlogPost
    fields = ["title", "content", "preview_img"]
    success_url = reverse_lazy("blog:blog_list")


class BlogUpdateView(UpdateView):
    model = BlogPost
    fields = ["title", "content", "preview_img"]
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse_lazy("blog:blog_detail", args=[self.kwargs.get("pk")])


class BlogDeleteView(DeleteView):
    model = BlogPost
    template_name = "blog/blogpost_confirm_delete.html"
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Стандартный заголовок{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="row">
    <div class="col">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand">Меню</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'blog:blog_list' %}">Все посты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog_create' %}">Создать пост</a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                        Перейдите к просмотру или созданию постов
                    </span>
                </div>
            </div>
        </nav>
    </div>
</div>
<div class="row">
    {% block content %}{% endblock %}
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}Удаление{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2"></div>
    <div class="col">
        <div class="card p-5">
            <h5 class="card-title">Вы действительно хотите удалить статью "{{object.title}}"?</h5>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
    <div class="col-2"></div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2"></div>
    <div class="col justify-text-center">
        <div class="card m-5">
            <img src="{{ object.preview_img.url }}" class="card-img-top w-100" style="height: 25rem" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">{{ object.content }}</p>
                <a href="{% url 'blog:blog_update' object.pk %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
    </div>
    <div class="col-2"></div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'blog/base.html' %}

{% block title %}Создать пост{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2"></div>
    <div class="col">
        <div class="card p-5">
            <h5 class="card-title">Создание поста</h5>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
                <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary">Отмена</a>
            </form>
        </div>
    </div>
    <div class="col-2"></div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'blog/base.html' %}

{% block title %}Все посты{% endblock %}

{% block content %}
<div class="row">
    {% for post in object_list %}
    <div class="col">
        <div class="card m-5">
            <img src="{{ post.preview_img.url }}" class="card-img-top w-100" style="height: 10rem" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content | truncatechars:300}}</p>
                <a href="{% url 'blog:blog_detail' post.pk %}" class="btn btn-primary">Перейти к статье</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}