blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig


app_name = BlogConfig.name

urlpatterns = [
    path("blog_list/", views.BlogListView.as_view(), name="blog_list"),
    path("blog_detail/<int:pk>/", views.BlogDetailView.as_view(), name="blog_detail"),
    path("blog_create/", views.BlogCreateView.as_view(), name="blog_create"),
    path("blog_update/<int:pk>/", views.BlogUpdateView.as_view(), name="blog_update"),
    path("blog_delete/<int:pk>/", views.BlogDeleteView.as_view(), name="blog_delete"),
]

catalog/urls.py
from django.urls import path
from . import views
from catalog.apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path("home/", views.ProductListView.as_view(), name="home"),
    path("product_detail/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("new_product/", views.ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update", views.ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete", views.ProductDeleteView.as_view(), name="product_delete"),
    path("contacts/", views.ContactsView.as_view(), name="contacts"),
    path("category_list/", views.CategoryListView.as_view(), name="category_list"),
    path("product_by_category/<int:pk_category>", views.ProductListByCategory.as_view(), name="product_by_category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import User


class Category(models.Model):

    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=255)

    def __str__(self):
        return f"Категория '{self.name}'"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]
        db_table = "categories_table"


class Product(models.Model):

    name = models.CharField(max_length=100)
    description = models.TextField(max_length=255)
    product_photo = models.ImageField(upload_to="product_photos/")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Продукт '{self.name}'"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ["name"]
        db_table = "products_table"
        permissions = [("can_unpublish_product", "Can unpublish product"),]


class Contacts(models.Model):

    city = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.city} {self.phone_number}"

    class Meta:
        verbose_name = "контакт"
        verbose_name_plural = "контакты"
        ordering = ["city"]
        db_table = "contacts_table"

catalog/forms.py
from django.forms import ModelForm, ValidationError
from .models import Product


banned_worlds = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]


class ProductModeratorForm(ModelForm):

    class Meta:
        model = Product
        fields = ["is_published"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.get("is_published").widget.attrs.update({"class": "form-check"})


class ProductForm(ModelForm):

    class Meta:
        model = Product
        fields = "__all__"
        exclude = ["owner", "is_published"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field, value in self.fields.items():
            if field == "name":
                value.widget.attrs.update({"placeholder": "Введите название товара"})
                value.label = "Название продукта"
            if field == "description":
                value.widget.attrs.update({"placeholder": "Введите описание товара"})
                value.label = "Описание продукта"
            if field == "product_photo":
                value.label = "Фото продукта"
            if field == "category":
                value.label = "Категория"
            if field == "price":
                value.label = "Цена"
            value.widget.attrs.update({"class": "form-control"})
            if field == "is_published":
                value.widget.attrs.update({"class": "form-check"})

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if float(price) < 0:
            raise ValidationError("Цена не может быть отрицательной")
        return price

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        description = cleaned_data.get("description")
        for world in banned_worlds:
            if world.lower() in name.lower():
                self.add_error("name", "Имя содержит запрещенные слова")
            elif world.lower() in description.lower():
                self.add_error("description", "Описание содержит запрещенные слова")
        return cleaned_data

catalog/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Product, Contacts, Category
from django.urls import reverse_lazy
from .forms import ProductForm, ProductModeratorForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .services import get_product_from_cache_or_db
from django.core.cache import cache
from config.settings import CACHE_ENABLED


class ProductListView(ListView):
    model = Product
    template_name = "catalog/home.html"

    def get_queryset(self):
        if CACHE_ENABLED:
            products_queryset = cache.get("product_list_queryset")
            if not products_queryset:
                products_queryset = Product.objects.all()
                cache.set("product_list_queryset", products_queryset, 60 * 15)
            return products_queryset
        products_queryset = Product.objects.all()
        return products_queryset


@method_decorator(cache_page(60 * 15), name="dispatch")
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("can_unpublish_product"):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product_delete_form.html"
    success_url = reverse_lazy("catalog:home")
    permission_required = "catalog.delete_product"


class ContactsView(LoginRequiredMixin, View):

    def get(self, request):
        contacts = Contacts.objects.all()
        context = {"object_list": contacts}
        return render(request, "catalog/contacts.html", context=context)

    def post(self, request):
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        return HttpResponse(f"Спасибо, {name} ({email})! Ваше сообщение получено. ({message})")


class CategoryListView(ListView):
    model = Category


class ProductListByCategory(ListView):
    model = Product
    template_name = "catalog/product_by_category.html"

    def get_queryset(self):
        category = self.kwargs.get("pk_category")
        product_by_category = get_product_from_cache_or_db(category)
        return product_by_category

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Стандартный заголовок{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="row">
    <div class="col-2">
        {% include 'catalog/includes/menu.html' %}
    </div>
    <div class="col-10 p-5">
        {% block content %}{% endblock %}
    </div>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block title %}Категории{% endblock %}

{% block content %}
<h3 style="text-align:center;">Категории</h3>
<div class="row">
    {% for category in object_list %}
    <div class="col-4 p-3">
        <div class="card mx-auto text-center mb-3 text-bg-light d-flex flex-column"
             style="height: 100px; max-width: 20rem;">
            <a href="{% url 'catalog:product_by_category' category.pk %}"><h3>{{ category.name }}</h3></a>
            <p>{{ category.description }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
<h2 class="text-center p-5">Контакты</h2>
<div class="row">
    <div class="col-6">
        <div class="card text-bg-light p-3">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Имя</label>
                    <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                           aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="email-form" class="form-label">E-mail</label>
                    <input type="email" name="email" class="form-control" id="email-form">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Сообщение</label>
                    <textarea class="form-control" name="message" id="exampleFormControlTextarea1" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
        </div>
    </div>
    <div class="col-6">
        <div class="card text-bg-light mb-3">
            <div class="card-header"><h5 class="mt-2 mb-2">Наши контакты</h5></div>
            <div class="card-body">
                {% for contact in object_list %}
                <div class="row p-2">
                    <div class="col">
                        {{contact.city}}
                    </div>
                    <div class="col">
                        {{contact.phone_number}}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<h3 style="text-align:center;">Главная</h3>
{% include 'catalog/includes/header.html' %}
<div class="row">
    {% for product in object_list %}
    {% if product.is_published %}
    <div class="col-4 p-3">
        <div class="card mx-auto text-center mb-3 text-bg-light d-flex flex-column"
             style="height: 220px; max-width: 20rem;">
            <a href="{% url 'catalog:product_detail' product.id %}"
               class="card-header link-offset-2 link-underline link-underline-opacity-0">{{product.name}}</a>
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">${{product.price}}</h5>
                <p class="card-text">{{product.description | truncatechars:100}}</p>
                <div class="d-grid gap-2 mt-auto">
                    <button type="button" class="mt-auto btn btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
<div class="row">
    <a href="{% url 'catalog:product_create' %}" class="btn btn-primary">Добавить новый товар</a>
</div>
{% endblock %}

catalog/templates/catalog/home_page.html
{% extends 'catalog/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<h3 style="text-align:center;">Главная</h3>
{% include 'catalog/includes/header.html' %}
<div class="row">
{% for product in products%}
    <div class="col-4 p-3">
        <div class="card mx-auto text-center mb-3 text-bg-light d-flex flex-column"
             style="height: 220px; max-width: 20rem;">
            <a href="{% url 'catalog:product_info' product.id %}" class="card-header link-offset-2 link-underline link-underline-opacity-0">{{product.name}}</a>
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">${{product.price}}</h5>
                <p class="card-text">{{product.description | truncatechars:100}}</p>
                <div class="d-grid gap-2 mt-auto">
                    <button type="button" class="mt-auto btn btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_by_category.html
{% extends 'catalog/base.html' %}

{% block title %}Продукты категории{% endblock %}

{% block content %}
<h3 style="text-align:center;">Продукты категории</h3>
<div class="row">
    {% for product in object_list %}
    <div class="col-4 p-3">
        <div class="card mx-auto text-center mb-3 text-bg-light d-flex flex-column"
             style="height: 220px; max-width: 20rem;">
            <a href="{% url 'catalog:product_detail' product.id %}"
               class="card-header link-offset-2 link-underline link-underline-opacity-0">{{product.name}}</a>
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">${{product.price}}</h5>
                <p class="card-text">{{product.description | truncatechars:100}}</p>
                <div class="d-grid gap-2 mt-auto">
                    <button type="button" class="mt-auto btn btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_delete_form.html
{% extends 'catalog/base.html' %}

{% block title %}Форма{% endblock %}

{% block content %}
<div class="container mt-3">
    <h1>Вы уверены, что хотите удалить элемент {{ product.name }}?</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Удалить</button>
        <a href="{% url 'catalog:home' %}" class="btn">Отмена</a>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block title %}{{product.name}}{% endblock %}

{% block content %}
<div class="container mt-3">
    <h1>{{object.name}}</h1>
    <ul class="list-group mt-3">
        <li class="list-group-item">
            <img src="{{object.product_photo.url | default:'[Photo]'}}" class="border rounded mx-auto d-block" style="max-width: 40%; height: 40%;" alt="...">
        </li>
        <li class="list-group-item">{{object.category}}</li>
        <li class="list-group-item">Цена: {{object.price}}</li>
        <li class="list-group-item">
            Описание:
            <p>{{object.description}}</p>
        </li>
    </ul>
    {% if perms.catalog.delete_product or user == product.owner %}
    <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-primary m-3">Изменить</a>
    <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger m-3">Удалить</a>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block title %}Форма{% endblock %}

{% block content %}
<div class="container mt-3">
    <h1>Форма продукта</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{% url 'catalog:home' %}" class="btn">Отмена</a>
    </form>
</div>
{% endblock %}